version: '{branch}-{build}'
branches:
  only:
  - /^v[0-9\.x]+$/
skip_non_tags: true
environment:
  RUBY_VERSION: 21
  GEM_INIT_DEPENDENCY: ocra bundler webrick minima jekyll-feed
  GITHUB_URL: https://github.com/altbdoor/jekyll-exe
  BUILD_INJECT_DEPS: digest/md5,webrick
  BUILD_BUNDLER_DEPS: minima,jekyll-feed
install:
- cmd: >-
    set PATH=C:\Program Files\Git\usr\bin;C:\Ruby%RUBY_VERSION%\bin;%PATH%

    gem sources --add https://rubygems.org

    bash -c "echo 'gem: --no-document' >> ~/.gemrc"

    gem install %GEM_INIT_DEPENDENCY%
build_script:
- cmd: >-
    appveyor DownloadFile "%GITHUB_URL%/raw/master/build.sh" -FileName "c:\projects\jekyll-exe\build.sh"

    bash "build.sh" "%APPVEYOR_REPO_TAG_NAME:stable-v=%" "%BUILD_INJECT_DEPS%" "%BUILD_BUNDLER_DEPS%"

    7z a jekyll.zip jekyll.exe > nul

    gem list --local > gem_list.log
test: off
artifacts:
- path: jekyll.zip
- path: ocra.log
- path: release.log
- path: gem_list.log
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: pre-$(appveyor_repo_tag_name)
  description: https://ci.appveyor.com/project/altbdoor/jekyll-exe/build/$(appveyor_repo_branch)-$(appveyor_build_number)
  auth_token:
    secure: O9Z6n0mhyhIEg0+ellL+7mOgZWYDi+upenUB+nNcDIVR1+fcqt3s6WkeiqYQblYq
  artifact: jekyll.zip,ocra.log,release.log,gem_list.log
  prerelease: true
  force_update: true
