version: '{branch}-{build}'
branches:
  only:
  - /^v[0-9\.x]+$/
skip_non_tags: true
environment:
  RUBY_VERSION: 22
  GEM_INIT_DEPENDENCY: ocra webrick
  GITHUB_URL: https://github.com/altbdoor/jekyll-exe
  BUILD_INJECT_DEPS: jekyll-watch,rouge,webrick
  BUILD_BUNDLER_DEPS: 
install:
- cmd: >-
    set PATH=C:\Program Files\Git\usr\bin;C:\Ruby%RUBY_VERSION%\bin;%PATH%

    gem install %GEM_INIT_DEPENDENCY% --no-document
build_script:
- cmd: >-
    appveyor DownloadFile "%GITHUB_URL%/raw/master/build.sh" -FileName "c:\projects\jekyll-exe\build.sh"

    bash "build.sh" "%APPVEYOR_REPO_TAG_NAME:stable-v=%" "%BUILD_INJECT_DEPS%" "%BUILD_BUNDLER_DEPS%"

    7z a jekyll.zip jekyll.exe > nul

    7z a logs.zip ocra.log release.log > nul
test: off
artifacts:
- path: jekyll.zip
- path: logs.zip
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: pre-$(appveyor_repo_tag_name)
  description: https://ci.appveyor.com/project/altbdoor/jekyll-exe/build/$(appveyor_repo_branch)-$(appveyor_build_number)
  auth_token:
    secure: O9Z6n0mhyhIEg0+ellL+7mOgZWYDi+upenUB+nNcDIVR1+fcqt3s6WkeiqYQblYq
  artifact: jekyll.zip,logs.zip
  prerelease: true
  force_update: true
